format = """
[╭─](bold 238)\
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$golang\
$python\
$nodejs\
$rust\
$package\
$line_break\
$character
"""

right_format = """
$status\
$cmd_duration\
$time\
$battery\
"""

add_newline = true
command_timeout = 1000

[os]
format = '[ $symbol](bold 056) '
disabled = false

[username]
format = '[$user]($style) '
style_user = "bold yellow"
style_root = "bold red"
show_always = true
aliases = { "aei" = "aei" }

[hostname]
ssh_only = true
ssh_symbol = " "
format = "on [$ssh_symbol$hostname](bold yellow) "
disabled = false

[directory]
style = "bold purple"
home_symbol = "  ~"
read_only = " 󰌾"
read_only_style = "197"
truncation_length = 1
truncate_to_repo = true
truncation_symbol = "…/"
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "󰊢 "
format = "on [$symbol$branch]($style)"
truncation_length = 4
truncation_symbol = "…/"
style = "bold green"

# Shows current git status
[git_status]
format = '([\($all_status$ahead_behind\)]($style) )'
style = 'bold green'
conflicted = '[🏳](red) '
up_to_date = '[ ](green) '
untracked = '[](red) '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '$⇣${count}'
stashed = '[󰏗 ](green) '
modified = '[](yellow) '
staged = '[++\($count\)](green) '
renamed = '[󰖷](yellow) '
deleted = '[ ](red) '

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
disabled = true

[cmd_duration]
min_time = 100
format = "took [$duration]($style) "
show_notifications = true
min_time_to_notify = 10000
disabled = false

[fill]
symbol = " "

[status]
disabled = false
symbol = "× "
format = '[$symbol$status( $common_meaning)( $signal_name)]($style) '
style = "bold red"

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style) "

[character]
success_symbol = "[╰─󰁔](bold 238) "
error_symbol = "[╰─󰁔](bold 238) "
vicmd_symbol = "[╰─󰁔](bold 238) "

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
disabled = false

[[battery.display]] 
threshold = 15
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 80
style = "bold green"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
format = "[$symbol$version]($style) "
style = "bold cyan"
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "喝 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
format = "[$symbol$version]($style) "
style = "bold green"
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = "󱗆 "

[python]
format = "[$symbol$version]($style) "
style = "bold yellow"
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
format = "[$symbol$version]($style) "
style = "bold red"
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "